# Generated by Django 4.2.5 on 2023-10-10 12:59

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.DecimalField(decimal_places=2, default=2.5, max_digits=3, validators=[django.core.validators.MinValueValidator(2.0, message='Weight can not be lower than 2.5 Kg'), django.core.validators.MaxValueValidator(650.0, message='Weight can not be more than 650KG')], verbose_name='User Weight')),
                ('height', models.DecimalField(decimal_places=2, default=45.0, max_digits=3, validators=[django.core.validators.MinValueValidator(45.0, message='Height can not be less than 45cm'), django.core.validators.MaxValueValidator(280, message='Height can not be taller than 280 cm tall')], verbose_name='User Height')),
                ('diabetes_type', models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2')], default='Type 1', max_length=6, verbose_name='Diabetes Type')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=6, verbose_name='User Sex')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GlucoseReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('blood_sugar_level', models.DecimalField(decimal_places=1, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
