# Generated by Django 4.2.5 on 2023-10-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glucosereading',
            options={'verbose_name_plural': 'User Glucose Readings'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['id'], 'verbose_name_plural': 'Users'},
        ),
    ]
