# Generated by Django 4.2.5 on 2023-10-10 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_glucosereading_options_alter_users_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='height',
            field=models.DecimalField(decimal_places=2, default=45.0, max_digits=5, validators=[django.core.validators.MinValueValidator(45.0, message='Height cannot be less than 45cm'), django.core.validators.MaxValueValidator(280.0, message='Height cannot be taller than 280 cm tall')], verbose_name='User Height'),
        ),
        migrations.AlterField(
            model_name='users',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, validators=[django.core.validators.MinValueValidator(2.0, message='Weight cannot be lower than 2.5 Kg'), django.core.validators.MaxValueValidator(650.0, message='Weight cannot be more than 650 KG')], verbose_name='User Weight'),
        ),
    ]
